//
// Created by Utsav Dhanuka on 04/07/23.
//

#ifndef RUBIKSCUBESOLVER_CORNERPATTERNDATABASE_H
#define RUBIKSCUBESOLVER_CORNERPATTERNDATABASE_H


class CornerPatternDatabase {

};


#endif //RUBIKSCUBESOLVER_CORNERPATTERNDATABASE_H
